"use client"

import { useState, useMemo } from "react"
import { Input } from "@/components/ui/input"
import VideoCard from "@/components/VideoCard"
import Pagination from "@/components/Pagination"

// Bu yerda barcha URL'larni joylashtiring
const videoUrls = [
    "https://s1.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00001_qism.mp4",
    "https://s1.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00009_qism.mp4",
    "https://s1.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00017_qism.mp4",
    "https://s1.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00025_qism.mp4",
    "https://s1.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00033_qism.mp4",
    "https://s1.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00041_qism.mp4",
    "https://s1.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00049_qism.mp4",
    "https://s1.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00057_qism.mp4",
    "https://s1.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00065_qism.mp4",
    "https://s1.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00073_qism.mp4",
    "https://s1.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00081_qism.mp4",
    "https://s1.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00089_qism.mp4",
    "https://s1.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00097_qism.mp4",
    "https://s1.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00105_qism.mp4",
    "https://s1.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00113_qism.mp4",
    "https://s1.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00121_qism.mp4",
    "https://s1.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00129_qism.mp4",
    "https://s1.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00137_qism.mp4",
    "https://s1.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00145_qism.mp4",
    "https://s1.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00153_qism.mp4",
    "https://s1.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00161_qism.mp4",
    "https://s1.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00169_qism.mp4",
    "https://s1.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00177_qism.mp4",
    "https://s1.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00185_qism.mp4",
    "https://s1.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00193_qism.mp4",
    "https://s1.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00201_qism.mp4",
    "https://s1.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00209_qism.mp4",
    "https://s1.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00217_qism.mp4",
    "https://s1.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00225_qism.mp4",
    "https://s1.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00233_qism.mp4",
    "https://s1.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00241_qism.mp4",
    "https://s2.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00002_qism.mp4",
    "https://s2.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00010_qism.mp4",
    "https://s2.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00018_qism.mp4",
    "https://s2.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00026_qism.mp4",
    "https://s2.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00034_qism.mp4",
    "https://s2.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00042_qism.mp4",
    "https://s2.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00050_qism.mp4",
    "https://s2.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00058_qism.mp4",
    "https://s2.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00066_qism.mp4",
    "https://s2.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00074_qism.mp4",
    "https://s2.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00082_qism.mp4",
    "https://s2.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00090_qism.mp4",
    "https://s2.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00098_qism.mp4",
    "https://s2.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00106_qism.mp4",
    "https://s2.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00114_qism.mp4",
    "https://s2.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00122_qism.mp4",
    "https://s2.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00130_qism.mp4",
    "https://s2.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00138_qism.mp4",
    "https://s2.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00146_qism.mp4",
    "https://s2.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00154_qism.mp4",
    "https://s2.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00162_qism.mp4",
    "https://s2.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00170_qism.mp4",
    "https://s2.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00178_qism.mp4",
    "https://s2.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00186_qism.mp4",
    "https://s2.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00194_qism.mp4",
    "https://s2.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00202_qism.mp4",
    "https://s2.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00210_qism.mp4",
    "https://s2.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00218_qism.mp4",
    "https://s2.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00226_qism.mp4",
    "https://s2.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00234_qism.mp4",
    "https://s2.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00242_qism.mp4",
    "https://s3.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00003_qism.mp4",
    "https://s3.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00011_qism.mp4",
    "https://s3.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00019_qism.mp4",
    "https://s3.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00027_qism.mp4",
    "https://s3.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00035_qism.mp4",
    "https://s3.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00043_qism.mp4",
    "https://s3.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00051_qism.mp4",
    "https://s3.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00059_qism.mp4",
    "https://s3.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00067_qism.mp4",
    "https://s3.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00075_qism.mp4",
    "https://s3.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00083_qism.mp4",
    "https://s3.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00091_qism.mp4",
    "https://s3.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00099_qism.mp4",
    "https://s3.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00107_qism.mp4",
    "https://s3.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00115_qism.mp4",
    "https://s3.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00123_qism.mp4",
    "https://s3.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00131_qism.mp4",
    "https://s3.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00139_qism.mp4",
    "https://s3.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00147_qism.mp4",
    "https://s3.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00155_qism.mp4",
    "https://s3.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00163_qism.mp4",
    "https://s3.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00171_qism.mp4",
    "https://s3.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00179_qism.mp4",
    "https://s3.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00187_qism.mp4",
    "https://s3.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00195_qism.mp4",
    "https://s3.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00203_qism.mp4",
    "https://s3.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00211_qism.mp4",
    "https://s3.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00219_qism.mp4",
    "https://s3.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00227_qism.mp4",
    "https://s3.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00235_qism.mp4",
    "https://s3.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00243_qism.mp4",
    "https://s4.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00004_qism.mp4",
    "https://s4.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00012_qism.mp4",
    "https://s4.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00020_qism.mp4",
    "https://s4.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00028_qism.mp4",
    "https://s4.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00036_qism.mp4",
    "https://s4.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00044_qism.mp4",
    "https://s4.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00052_qism.mp4",
    "https://s4.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00060_qism.mp4",
    "https://s4.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00068_qism.mp4",
    "https://s4.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00076_qism.mp4",
    "https://s4.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00084_qism.mp4",
    "https://s4.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00092_qism.mp4",
    "https://s4.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00100_qism.mp4",
    "https://s4.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00108_qism.mp4",
    "https://s4.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00116_qism.mp4",
    "https://s4.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00124_qism.mp4",
    "https://s4.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00132_qism.mp4",
    "https://s4.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00140_qism.mp4",
    "https://s4.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00148_qism.mp4",
    "https://s4.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00156_qism.mp4",
    "https://s4.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00164_qism.mp4",
    "https://s4.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00172_qism.mp4",
    "https://s4.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00180_qism.mp4",
    "https://s4.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00188_qism.mp4",
    "https://s4.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00196_qism.mp4",
    "https://s4.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00204_qism.mp4",
    "https://s4.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00212_qism.mp4",
    "https://s4.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00220_qism.mp4",
    "https://s4.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00228_qism.mp4",
    "https://s4.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00236_qism.mp4",
    "https://s4.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00244_qism.mp4",
    "https://s5.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00005_qism.mp4",
    "https://s5.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00013_qism.mp4",
    "https://s5.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00021_qism.mp4",
    "https://s5.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00029_qism.mp4",
    "https://s5.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00037_qism.mp4",
    "https://s5.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00045_qism.mp4",
    "https://s5.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00053_qism.mp4",
    "https://s5.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00061_qism.mp4",
    "https://s5.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00069_qism.mp4",
    "https://s5.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00077_qism.mp4",
    "https://s5.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00085_qism.mp4",
    "https://s5.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00093_qism.mp4",
    "https://s5.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00101_qism.mp4",
    "https://s5.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00109_qism.mp4",
    "https://s5.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00117_qism.mp4",
    "https://s5.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00125_qism.mp4",
    "https://s5.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00133_qism.mp4",
    "https://s5.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00141_qism.mp4",
    "https://s5.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00149_qism.mp4",
    "https://s5.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00157_qism.mp4",
    "https://s5.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00165_qism.mp4",
    "https://s5.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00173_qism.mp4",
    "https://s5.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00181_qism.mp4",
    "https://s5.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00189_qism.mp4",
    "https://s5.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00197_qism.mp4",
    "https://s5.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00205_qism.mp4",
    "https://s5.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00213_qism.mp4",
    "https://s5.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00221_qism.mp4",
    "https://s5.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00229_qism.mp4",
    "https://s5.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00237_qism.mp4",
    "https://s5.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00245_qism.mp4",
    "https://s6.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00006_qism.mp4",
    "https://s6.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00014_qism.mp4",
    "https://s6.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00022_qism.mp4",
    "https://s6.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00030_qism.mp4",
    "https://s6.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00038_qism.mp4",
    "https://s6.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00046_qism.mp4",
    "https://s6.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00054_qism.mp4",
    "https://s6.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00062_qism.mp4",
    "https://s6.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00070_qism.mp4",
    "https://s6.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00078_qism.mp4",
    "https://s6.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00086_qism.mp4",
    "https://s6.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00094_qism.mp4",
    "https://s6.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00102_qism.mp4",
    "https://s6.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00110_qism.mp4",
    "https://s6.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00118_qism.mp4",
    "https://s6.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00126_qism.mp4",
    "https://s6.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00134_qism.mp4",
    "https://s6.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00142_qism.mp4",
    "https://s6.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00150_qism.mp4",
    "https://s6.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00158_qism.mp4",
    "https://s6.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00166_qism.mp4",
    "https://s6.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00174_qism.mp4",
    "https://s6.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00182_qism.mp4",
    "https://s6.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00190_qism.mp4",
    "https://s6.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00198_qism.mp4",
    "https://s6.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00206_qism.mp4",
    "https://s6.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00214_qism.mp4",
    "https://s6.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00222_qism.mp4",
    "https://s6.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00230_qism.mp4",
    "https://s6.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00238_qism.mp4",
    "https://s6.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00246_qism.mp4",
    "https://s7.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00007_qism.mp4",
    "https://s7.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00015_qism.mp4",
    "https://s7.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00023_qism.mp4",
    "https://s7.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00031_qism.mp4",
    "https://s7.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00039_qism.mp4",
    "https://s7.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00047_qism.mp4",
    "https://s7.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00055_qism.mp4",
    "https://s7.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00063_qism.mp4",
    "https://s7.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00071_qism.mp4",
    "https://s7.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00079_qism.mp4",
    "https://s7.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00087_qism.mp4",
    "https://s7.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00095_qism.mp4",
    "https://s7.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00103_qism.mp4",
    "https://s7.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00111_qism.mp4",
    "https://s7.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00119_qism.mp4",
    "https://s7.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00127_qism.mp4",
    "https://s7.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00135_qism.mp4",
    "https://s7.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00143_qism.mp4",
    "https://s7.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00151_qism.mp4",
    "https://s7.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00159_qism.mp4",
    "https://s7.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00167_qism.mp4",
    "https://s7.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00175_qism.mp4",
    "https://s7.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00183_qism.mp4",
    "https://s7.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00191_qism.mp4",
    "https://s7.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00199_qism.mp4",
    "https://s7.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00207_qism.mp4",
    "https://s7.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00215_qism.mp4",
    "https://s7.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00223_qism.mp4",
    "https://s7.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00231_qism.mp4",
    "https://s7.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00239_qism.mp4",
    "https://s7.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00247_qism.mp4",
    "https://s8.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00008_qism.mp4",
    "https://s8.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00016_qism.mp4",
    "https://s8.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00024_qism.mp4",
    "https://s8.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00032_qism.mp4",
    "https://s8.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00040_qism.mp4",
    "https://s8.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00048_qism.mp4",
    "https://s8.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00056_qism.mp4",
    "https://s8.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00064_qism.mp4",
    "https://s8.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00072_qism.mp4",
    "https://s8.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00080_qism.mp4",
    "https://s8.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00088_qism.mp4",
    "https://s8.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00096_qism.mp4",
    "https://s8.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00104_qism.mp4",
    "https://s8.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00112_qism.mp4",
    "https://s8.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00120_qism.mp4",
    "https://s8.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00128_qism.mp4",
    "https://s8.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00136_qism.mp4",
    "https://s8.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00144_qism.mp4",
    "https://s8.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00152_qism.mp4",
    "https://s8.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00160_qism.mp4",
    "https://s8.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00168_qism.mp4",
    "https://s8.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00176_qism.mp4",
    "https://s8.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00184_qism.mp4",
    "https://s8.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00192_qism.mp4",
    "https://s8.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00200_qism.mp4",
    "https://s8.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00208_qism.mp4",
    "https://s8.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00216_qism.mp4",
    "https://s8.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00224_qism.mp4",
    "https://s8.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00232_qism.mp4",
    "https://s8.faylmovi.ru/tarjima_seriallar/Senga_Oshiqman_00240_qism.mp4"
]

function extractEpisodeNumber(url: string): number {
  const match = url.match(/Senga_Oshiqman_(\d+)_qism/)
  return match ? Number.parseInt(match[1], 10) : 0
}

export default function Home() {
  const [searchTerm, setSearchTerm] = useState("")
  const [currentPage, setCurrentPage] = useState(1)
  const itemsPerPage = 20

  const sortedVideos = useMemo(() => {
    return videoUrls
      .map((url) => ({
        id: extractEpisodeNumber(url),
        title: `Senga Oshiqman ${extractEpisodeNumber(url).toString().padStart(3, "0")}-qism`,
        url: url,
      }))
      .sort((a, b) => a.id - b.id)
  }, [])

  const filteredVideos = sortedVideos.filter((video) => video.title.toLowerCase().includes(searchTerm.toLowerCase()))

  const indexOfLastVideo = currentPage * itemsPerPage
  const indexOfFirstVideo = indexOfLastVideo - itemsPerPage
  const currentVideos = filteredVideos.slice(indexOfFirstVideo, indexOfLastVideo)

  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-8 text-center text-blue-300">Senga Oshiqman</h1>
      <Input
        type="search"
        placeholder="Qismni qidiring..."
        className="mb-6 bg-slate-800 text-slate-100 border-slate-700"
        value={searchTerm}
        onChange={(e) => setSearchTerm(e.target.value)}
      />
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
        {currentVideos.map((video) => (
          <VideoCard key={video.id} video={video} />
        ))}
      </div>
      <Pagination
        totalItems={filteredVideos.length}
        itemsPerPage={itemsPerPage}
        currentPage={currentPage}
        onPageChange={setCurrentPage}
      />
    </div>
  )
}

